name: Studento
description: A Student Assistant App for O/A level students.

dependencies:
  flutter:
    sdk: flutter
  device_info: "^0.2.0"
  connectivity: "^0.3.0"
  shared_preferences: "0.4.1"
  jaguar_flutter_asset: ^1.1.5
  flutter_webview_plugin: "^0.1.5"
  url_launcher: "^3.0.0"
  launch_review: "^1.0.1"
  numberpicker: "^0.1.0"
  # flutter_search_bar: "^2.0.3" # not used right now
  path_provider: "^0.4.0"
  flutter_staggered_grid_view: "^0.1.3"
  simple_permissions: "^0.1.3"

  sqflite: "^0.8.9"
  quiver: '>=0.29.0 <0.30.0'
  intl: "^0.15.6"
  firebase_analytics: "^0.3.3"
  firebase_core: any

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/physics-background-img.jpg
    - assets/icons/menu.svg
    - assets/icons/exam_icon.png
    - assets/icons/schedule_icon.png
    - assets/icons/notes_icon.png
    - assets/icons/todo-list_icon.png
    - assets/json/quotes.json
    - assets/json/subjects_list.json
    - assets/json/subjects_syllabus_urls.json
    - assets/json/subjects_topic_lists.json
    # TODO Uncomment once we move over all the files.
    # - assets/html/
    # - assets/html/past-papers/
    # - assets/html/topic-notes/

    # - assets/html/past-papers/2010/
    # - assets/html/past-papers/2210/
    # - assets/html/past-papers/2251/
    # - assets/html/past-papers/2281/
    # - assets/html/past-papers/4024/
    # - assets/html/past-papers/4037/
    # - assets/html/past-papers/5054/
    # - assets/html/past-papers/5070/
    - assets/html/past-papers/5090/
    # - assets/html/past-papers/6043/
    # - assets/html/past-papers/7048/
    # - assets/html/past-papers/7110/
    # - assets/html/past-papers/7115/
    # - assets/html/past-papers/7707/
    # - assets/html/past-papers/8021/
    # - assets/html/past-papers/8682/
    # - assets/html/past-papers/9071/
    # - assets/html/past-papers/9093/
    # - assets/html/past-papers/9608/
    # - assets/html/past-papers/9699/
    # - assets/html/past-papers/9700/
    - assets/html/past-papers/9702/
    # - assets/html/past-papers/9705/
    - assets/html/past-papers/9706/
    # - assets/html/past-papers/9708/
    # - assets/html/past-papers/9709/
    # - assets/html/past-papers/9716/

    # - assets/html/past-papers/assets/2010/
    # - assets/html/past-papers/assets/2210/
    # - assets/html/past-papers/assets/2251/
    # - assets/html/past-papers/assets/2281/
    # - assets/html/past-papers/assets/4024/
    # - assets/html/past-papers/assets/4037/
    # - assets/html/past-papers/assets/5054/
    # - assets/html/past-papers/assets/5070/
    # - assets/html/past-papers/assets/5090/
    # - assets/html/past-papers/assets/6043/
    # - assets/html/past-papers/assets/7048/
    # - assets/html/past-papers/assets/7110/
    # - assets/html/past-papers/assets/7115/
    # - assets/html/past-papers/assets/7707/
    # - assets/html/past-papers/assets/8021/
    # - assets/html/past-papers/assets/8682/
    # - assets/html/past-papers/assets/9071/
    # - assets/html/past-papers/assets/9093/
    # - assets/html/past-papers/assets/9608/
    # - assets/html/past-papers/assets/9699/
    # - assets/html/past-papers/assets/9700/
    # - assets/html/past-papers/assets/9702/
    # - assets/html/past-papers/assets/9705/
    # - assets/html/past-papers/assets/9706/
    # - assets/html/past-papers/assets/9708/
    # - assets/html/past-papers/assets/9709/
    # - assets/html/past-papers/assets/9716/


    # - assets/html/topic-notes/2010/
    # - assets/html/topic-notes/2210/
    # - assets/html/topic-notes/2251/
    # - assets/html/topic-notes/2281/
    # - assets/html/topic-notes/4024/
    # - assets/html/topic-notes/4037/
    - assets/html/topic-notes/5054/
    # - assets/html/topic-notes/5070/
    - assets/html/topic-notes/5090/
    # - assets/html/topic-notes/6043/
    # - assets/html/topic-notes/7048/
    # - assets/html/topic-notes/7110/
    # - assets/html/topic-notes/7115/
    - assets/html/topic-notes/7707/
    # - assets/html/topic-notes/8021/
    # - assets/html/topic-notes/8682/
    # - assets/html/topic-notes/9071/
    # - assets/html/topic-notes/9093/
    # - assets/html/topic-notes/9608/
    # - assets/html/topic-notes/9699/
    - assets/html/topic-notes/9700/
    # - assets/html/topic-notes/9702/
    # - assets/html/topic-notes/9705/
    - assets/html/topic-notes/9706/
    # - assets/html/topic-notes/9708/
    # - assets/html/topic-notes/9709/
    # - assets/html/topic-notes/9716/

    # - assets/html/topic-notes/assets/2010/
    # - assets/html/topic-notes/assets/2210/
    # - assets/html/topic-notes/assets/2251/
    # - assets/html/topic-notes/assets/2281/
    # - assets/html/topic-notes/assets/4024/
    # - assets/html/topic-notes/assets/4037/
    # - assets/html/topic-notes/assets/5054/
    # - assets/html/topic-notes/assets/5070/
    # - assets/html/topic-notes/assets/5090/
    # - assets/html/topic-notes/assets/6043/
    # - assets/html/topic-notes/assets/7048/
    # - assets/html/topic-notes/assets/7110/
    # - assets/html/topic-notes/assets/7115/
    # - assets/html/topic-notes/assets/7707/
    # - assets/html/topic-notes/assets/8021/
    # - assets/html/topic-notes/assets/8682/
    # - assets/html/topic-notes/assets/9071/
    # - assets/html/topic-notes/assets/9093/
    # - assets/html/topic-notes/assets/9608/
    # - assets/html/topic-notes/assets/9699/
    # - assets/html/topic-notes/assets/9700/
    # - assets/html/topic-notes/assets/9702/
    # - assets/html/topic-notes/assets/9705/
    # - assets/html/topic-notes/assets/9706/
    # - assets/html/topic-notes/assets/9708/
    # - assets/html/topic-notes/assets/9709/
    # - assets/html/topic-notes/assets/9716/

    - assets/text/background1.jpg
    - assets/text/background2.jpg
    - assets/text/background3.jpg
    - assets/text/background4.jpg
    - assets/text/background5.jpg
    - assets/text/background6.jpg
    - assets/text/background7.jpg
    - assets/text/background8.jpg


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Mina
      fonts:
        - asset: assets/fonts/Mina/Mina-Bold.ttf
          weight: 700
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat/Montserrat-ExtraBoldItalic.ttf
          style: italic
          weight: 800